### ISSUE TITLE
Adding to existing project fails with "Previous coverage results not found, cannot report on evolution."

### ISSUE THREAD

**Issue by OldhamMade** [ewjoachim/coverage-comment-action#24]
When adding to an existing project, the action fails with "Previous coverage results not found, cannot report on evolution."

I think it would be preferable if this wasn't an explicit exception, but instead was part of the PR comment so that it can succeed to some extent.

**Comment by ewjoachim** [comment]
It's normal that this is printed, but it should not fail. The exception is voluntarily silenced. Do you want to share the details of the failed run ? Maybe it was something else ?

https://github.com/ewjoachim/coverage-comment-action/blob/28660cb669950dce9971264641238daf739f5f35/src/entrypoint#L258-L260

**Comment by OldhamMade** [comment]
Apologies, yes: checking the output, I misinterpreted the error:
```text
27 Traceback (most recent call last):
28   File "/usr/local/bin/entrypoint", line 296, in <module>
29     main()
30   File "/usr/local/bin/entrypoint", line 34, in main
31     comment = get_markdown_comment(
32   File "/usr/local/bin/entrypoint", line 179, in get_markdown_comment
33     coverage = coverage_info["@line-rate"] * 100
34 KeyError: '@line-rate'
35 Starting action
36 Operating on refs/pull/23/merge
37 Commenting on the coverage on PR 23
38 Previous coverage results not found, cannot report on evolution.
```

Not sure if this matters, but the `coverage.xml` doesn't exist as part of the repo. It is generated in a previous step in the workflow.

**Comment by OldhamMade** [comment]
Also, this is a private repo.

**Comment by OldhamMade** [comment]
Further investigation indicates that this isn't an error; the XML that is generated by my coverage tool doesn't contain any `line-rate` attributes. Apologies! Closing this ticket.

**Comment by ewjoachim** [comment]
Well This is a problem still. Or at least it could be mitigated.

**Comment by ewjoachim** [comment]
is the info present in another form or is it absent from the file completely ?

**Comment by OldhamMade** [comment]
> is the info present in another form or is it absent from the file completely ?

It is not a Cobertura-formatted XML file, unfortunately. I'm looking for an alternative plugin.

**Comment by ewjoachim** [comment]
Ah.

(I'm considering evolving the project to a different format, because cobertura xml, which I believed was a standard, is actually an ill-defined non-standard. And there's no universal standard at all :/)

**Comment by OldhamMade** [comment]
Interesting. So I'm using a tool that exports xml/json for https://coveralls.io.

One option could be using a set of XSL stylesheets to convert the various XML formats to a preferred XML format for ingest.
