### ISSUE TITLE
New subprocess error "detected dubious ownership in repository at '/github/workspace'"

### ISSUE THREAD

**Issue by dustinchilson** [ewjoachim/coverage-comment-action#61]
Seems this has the same issue as py-cov-action/python-coverage-comment-action#127

**Comment by ewjoachim** [comment]
I'm surprised that there are people using this action :) I'm really not invested making things very usable on this action, but it's nice if it's still valuable for some people :)

I'll try to issue a fix.

**Comment by ewjoachim** [comment]
https://github.com/ewjoachim/coverage-comment-action/commit/e361e7538a9741f4dfdcc252280c432ceaf88fcb

Tell me if it fixes things for you :)

**Comment by dustinchilson** [comment]
That fixed the issue.

I appreciate the quick fix.
